### ISSUE TITLE
Node 17, deprecation `main field` warning package.json

### ISSUE THREAD

**Issue by TarikGul** [dappforce/subsocial-js#77]
rel: [@substrate/api-sidecar#771](https://github.com/paritytech/substrate-api-sidecar/issues/771)

The warning was found when running substrate-api-sidecar with `@polkadot/apps-config@0.98.2-94`. 

`2021-11-23 12:07:47 error: (node:20453) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/aggron/dev/parity/substrate-api-sidecar/node_modules/@subsocial/utils/package.json' of 'build/index.js'. Please either fix that or report it to the module author`

Sidecar: v11.3.1
Node: v17 and up.

Being that Node v16 is the `Active LTS` right now, and 17 is `Current` I don't think it's a major problem, but I thought it was worth documenting.

**Comment by TarikGul** [comment]
Any update on this issue, is this repo actively maintained?

**Comment by olehmell** [comment]
> Any update on this issue, is this repo actively maintained?

HI. Yes. Which version of @subsocial/utils are you using?

**Comment by olehmell** [comment]
Current latest version subsocial SDK libs: `0.6.5`

**Comment by olehmell** [comment]
Ah ok, I made PR to apps-config, wait :)

**Comment by TarikGul** [comment]
Thanks again for updating that, the issue is fixed on our end. Closing.
