### ISSUE TITLE
Can't receive blocks

### ISSUE THREAD

**Issue by Asmadek** [dappforce/subsocial-js#83]
Use polkadot api, I am triing to receive blocks from subsocial-parachain for subquery, but receive such error. 

`
Unable to retrieve the specified block details. -32603: Unknown error occurred: Client, Application, UnknownBlock, State already discarded for BlockId::Hash, 0x4a12be580bb959937a1c7a61d5cf24428ed67fa571974b4007645d1886e7c89f
`
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpara.subsocial.network#/explorer/query/1

I can receive only blocks from last two hours. Can I receive older blocks?

**Comment by olehmell** [comment]
Hello, wait for the archive node for our parachain. I think we can prepare the node next week.
